// const fruits = ["Banana", "Orange", "Apple", "Mango"];
// console.log(fruits);
// console.log(fruits.length);
// console.log(fruits.toString());
// console.log(fruits.at(1));
// console.log(fruits[1]);
// console.log(fruits.join('-'));
// console.log(fruits.pop());
// console.log(fruits);
// console.log(fruits.push('Item01'));
// console.log(fruits);
// console.log(fruits.shift());
// console.log(fruits);
// console.log(fruits.unshift('Item01'));
// console.log(fruits);
// fruits.shift();
// console.log(fruits);
// const myGirls = ["Cecilie", "Lone"];
// const myBoys = ["Emil", "Tobias", "Linus"];
// console.log(myGirls.concat('Girls1'));
// console.log(myGirls);
// console.log(myBoys);
const fruits = ["Banana", "Orange", "Apple", "Mango"];
fruits.copyWithin(2, 1); 
console.log(fruits);